name: Build Test

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - '*'

  workflow_dispatch:

jobs:
  build-test:
    name: Build Test
    runs-on: ${{ matrix.environment }}
    strategy:
      matrix:
        environment:
          - ubuntu-latest

    env:
      DOTNET_NOLOGO: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      Configuration: 'Release'
      Solution: '*.sln'

    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET 8.x SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Nuget Restore
        run: dotnet restore

      - name: Build Solution
        run: |
          dotnet build ${{ env.Solution }} --configuration ${{ env.Configuration }} /p:ContinuousIntegrationBuild=true --no-restore

      - name: Run Unit Tests
        run: |
          dotnet test --configuration ${{ env.Configuration }} --no-build
